-- Phase 4 PROPOSED ONLY. Do not apply until final Product Owner approval.
-- Lock order for catalogue mutations: category/brand (when relevant) -> product -> variant -> price.

alter table public.categories add column active boolean not null default true, add column updated_at timestamptz not null default now();
alter table public.brands add column active boolean not null default true, add column updated_at timestamptz not null default now();
create table public.catalogue_prices (
 id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete restrict, variant_id uuid,
 condition public.product_condition not null, selling_price numeric(14,2) not null check(selling_price >= 0), active boolean not null default true,
 created_by uuid not null references public.profiles(id) on delete restrict, updated_by uuid not null references public.profiles(id) on delete restrict,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 foreign key(variant_id, product_id) references public.product_variants(id, product_id) on delete restrict
);
create unique index catalogue_prices_identity_key on public.catalogue_prices(product_id, coalesce(variant_id, '00000000-0000-0000-0000-000000000000'::uuid), condition);
create index catalogue_prices_active_lookup_idx on public.catalogue_prices(product_id, variant_id, condition) where active;
alter table public.catalogue_prices enable row level security;
create policy "management read catalogue prices" on public.catalogue_prices for select using (public.current_role() in ('ADMIN','MANAGER'));
revoke all on table public.catalogue_prices from anon;
revoke all on table public.catalogue_prices from authenticated;
grant select on table public.catalogue_prices to authenticated;

create or replace function public.require_catalogue_manager() returns uuid language plpgsql security definer set search_path=public as $$
declare actor uuid := auth.uid(); begin perform public.require_active_profile(); if public.current_role() not in ('ADMIN','MANAGER') then raise insufficient_privilege using message='Admin or Manager catalogue authority is required'; end if; return actor; end $$;
create or replace function public.lock_active_parents(p_category uuid,p_brand uuid) returns void language plpgsql security definer set search_path=public as $$
declare is_active boolean; begin if p_category is not null then select active into is_active from public.categories where id=p_category for key share; if is_active is distinct from true then raise exception 'An active product requires an active category'; end if; end if; if p_brand is not null then select active into is_active from public.brands where id=p_brand for key share; if is_active is distinct from true then raise exception 'An active product requires an active brand'; end if; end if; end $$;
create or replace function public.catalogue_audit(p_actor uuid,p_action text,p_type text,p_id uuid,p_before jsonb,p_after jsonb) returns void language plpgsql security definer set search_path=public as $$ begin insert into public.audit_logs(actor_id,action,entity_type,entity_id,before_data,after_data) values(p_actor,p_action,p_type,p_id,p_before,p_after); end $$;
create or replace function public.forbid_catalogue_delete() returns trigger language plpgsql as $$ begin raise exception 'Catalogue records are archived/deactivated; hard deletion is prohibited'; end $$;
create trigger categories_updated before update on public.categories for each row execute function public.touch_updated_at();
create trigger brands_updated before update on public.brands for each row execute function public.touch_updated_at();
create trigger catalogue_prices_updated before update on public.catalogue_prices for each row execute function public.touch_updated_at();
create trigger no_delete_categories before delete on public.categories for each row execute function public.forbid_catalogue_delete();
create trigger no_delete_brands before delete on public.brands for each row execute function public.forbid_catalogue_delete();
create trigger no_delete_products before delete on public.products for each row execute function public.forbid_catalogue_delete();
create trigger no_delete_variants before delete on public.product_variants for each row execute function public.forbid_catalogue_delete();
create trigger no_delete_prices before delete on public.catalogue_prices for each row execute function public.forbid_catalogue_delete();

create or replace function public.catalogue_create_category(p_name text) returns public.categories language plpgsql security definer set search_path=public as $$ declare a uuid:=public.require_catalogue_manager(); r public.categories; begin insert into public.categories(name) values(btrim(p_name)) returning * into r; perform public.catalogue_audit(a,'CATALOGUE_CATEGORY_CREATED','CATEGORY',r.id,null,to_jsonb(r)); return r; end $$;
create or replace function public.catalogue_update_category(p_id uuid,p_name text,p_active boolean) returns public.categories language plpgsql security definer set search_path=public as $$ declare a uuid:=public.require_catalogue_manager(); b public.categories;r public.categories;begin select * into b from public.categories where id=p_id for update;if not found then raise exception 'Category not found';end if;if not p_active and exists(select 1 from public.products where category_id=p_id and active) then raise exception 'Deactivate active products before deactivating their category';end if;update public.categories set name=btrim(p_name),active=p_active where id=p_id returning * into r;perform public.catalogue_audit(a,'CATALOGUE_CATEGORY_UPDATED','CATEGORY',r.id,to_jsonb(b),to_jsonb(r));return r;end $$;
create or replace function public.catalogue_create_brand(p_name text) returns public.brands language plpgsql security definer set search_path=public as $$ declare a uuid:=public.require_catalogue_manager();r public.brands;begin insert into public.brands(name) values(btrim(p_name)) returning * into r;perform public.catalogue_audit(a,'CATALOGUE_BRAND_CREATED','BRAND',r.id,null,to_jsonb(r));return r;end $$;
create or replace function public.catalogue_update_brand(p_id uuid,p_name text,p_active boolean) returns public.brands language plpgsql security definer set search_path=public as $$ declare a uuid:=public.require_catalogue_manager();b public.brands;r public.brands;begin select * into b from public.brands where id=p_id for update;if not found then raise exception 'Brand not found';end if;if not p_active and exists(select 1 from public.products where brand_id=p_id and active) then raise exception 'Deactivate active products before deactivating their brand';end if;update public.brands set name=btrim(p_name),active=p_active where id=p_id returning * into r;perform public.catalogue_audit(a,'CATALOGUE_BRAND_UPDATED','BRAND',r.id,to_jsonb(b),to_jsonb(r));return r;end $$;

create or replace function public.catalogue_create_product(p_name text,p_sku text,p_barcode text,p_model text,p_description text,p_category uuid,p_brand uuid,p_serialized boolean,p_min_stock integer,p_warranty integer) returns public.products language plpgsql security definer set search_path=public as $$ declare a uuid:=public.require_catalogue_manager();r public.products;begin perform public.lock_active_parents(p_category,p_brand);insert into public.products(name,sku,barcode,model,description,category_id,brand_id,serialized,minimum_stock,warranty_months,created_by) values(btrim(p_name),p_sku,nullif(btrim(p_barcode),''),nullif(btrim(p_model),''),nullif(btrim(p_description),''),p_category,p_brand,p_serialized,p_min_stock,p_warranty,a) returning * into r;perform public.catalogue_audit(a,'CATALOGUE_PRODUCT_CREATED','PRODUCT',r.id,null,to_jsonb(r));return r;end $$;
create or replace function public.catalogue_update_product(p_id uuid,p_name text,p_sku text,p_barcode text,p_model text,p_description text,p_category uuid,p_brand uuid,p_serialized boolean,p_min_stock integer,p_warranty integer,p_active boolean) returns public.products language plpgsql security definer set search_path=public as $$ declare a uuid:=public.require_catalogue_manager();b public.products;r public.products;begin perform public.lock_active_parents(p_category,p_brand);select * into b from public.products where id=p_id for update;if not found then raise exception 'Product not found';end if;if not b.active then raise exception 'Archived products require a separate approved reactivation workflow';end if;if not p_active then raise exception 'Use catalogue_archive_product for safe product deactivation';end if;update public.products set name=btrim(p_name),sku=p_sku,barcode=nullif(btrim(p_barcode),''),model=nullif(btrim(p_model),''),description=nullif(btrim(p_description),''),category_id=p_category,brand_id=p_brand,serialized=p_serialized,minimum_stock=p_min_stock,warranty_months=p_warranty,active=true where id=p_id returning * into r;perform public.catalogue_audit(a,'CATALOGUE_PRODUCT_UPDATED','PRODUCT',r.id,to_jsonb(b),to_jsonb(r));return r;end $$;
create or replace function public.catalogue_archive_product(p_id uuid) returns public.products language plpgsql security definer set search_path=public as $$ declare a uuid:=public.require_catalogue_manager();b public.products;r public.products;vb jsonb;va jsonb;pb jsonb;pa jsonb;begin select * into b from public.products where id=p_id for update;if not found then raise exception 'Product not found';end if;perform 1 from public.stock_buckets where product_id=p_id and quantity>0 for key share;if found then raise exception 'A product with current non-serialized inventory cannot be archived';end if;perform 1 from public.serialized_units where product_id=p_id and status='AVAILABLE' for key share;if found then raise exception 'A product with current available serialized inventory cannot be archived';end if;select coalesce(jsonb_agg(to_jsonb(x)),'[]') into vb from (select * from public.product_variants where product_id=p_id and active for update) x;select coalesce(jsonb_agg(to_jsonb(x)),'[]') into pb from (select * from public.catalogue_prices where product_id=p_id and active for update) x;with u as (update public.catalogue_prices set active=false,updated_by=a where product_id=p_id and active returning *) select coalesce(jsonb_agg(to_jsonb(u)),'[]') into pa from u;with u as (update public.product_variants set active=false where product_id=p_id and active returning *) select coalesce(jsonb_agg(to_jsonb(u)),'[]') into va from u;update public.products set active=false where id=p_id returning * into r;perform public.catalogue_audit(a,'CATALOGUE_PRODUCT_ARCHIVED','PRODUCT',r.id,jsonb_build_object('product',to_jsonb(b),'variants',vb,'prices',pb),jsonb_build_object('product',to_jsonb(r),'variants',va,'prices',pa));return r;end $$;

create or replace function public.catalogue_create_variant(p_product uuid,p_label text,p_sku text,p_barcode text,p_attributes jsonb) returns public.product_variants language plpgsql security definer set search_path=public as $$ declare a uuid:=public.require_catalogue_manager();r public.product_variants;begin perform 1 from public.products where id=p_product and active for update;if not found then raise exception 'A variant requires an active parent product';end if;insert into public.product_variants(product_id,label,sku,barcode,attributes,active) values(p_product,btrim(p_label),nullif(btrim(p_sku),''),nullif(btrim(p_barcode),''),coalesce(p_attributes,'{}'::jsonb),false) returning * into r;perform public.catalogue_audit(a,'CATALOGUE_VARIANT_CREATED_INACTIVE','PRODUCT_VARIANT',r.id,null,to_jsonb(r));return r;end $$;
create or replace function public.catalogue_update_variant(p_id uuid,p_label text,p_sku text,p_barcode text,p_attributes jsonb,p_active boolean) returns public.product_variants language plpgsql security definer set search_path=public as $$ declare a uuid:=public.require_catalogue_manager();b public.product_variants;r public.product_variants;pb jsonb;pa jsonb;begin select v.* into b from public.product_variants v join public.products p on p.id=v.product_id where v.id=p_id for update of p,v;if not found then raise exception 'Product variant not found';end if;if not p_active then raise exception 'Use catalogue_archive_variant for safe variant deactivation';end if;if not exists(select 1 from public.products where id=b.product_id and active) then raise exception 'An active variant requires an active parent product';end if;perform 1 from public.catalogue_prices where product_id=b.product_id and variant_id is null and active for update;if found then raise exception 'Deactivate product-level prices before activating variants';end if;select coalesce(jsonb_agg(to_jsonb(x)),'[]') into pb from (select * from public.catalogue_prices where variant_id=p_id for update) x;if not b.active and pb='[]'::jsonb then raise exception 'Configure a variant-specific price before activating a variant';end if;update public.product_variants set label=btrim(p_label),sku=nullif(btrim(p_sku),''),barcode=nullif(btrim(p_barcode),''),attributes=coalesce(p_attributes,'{}'::jsonb),active=true where id=p_id returning * into r;with u as (update public.catalogue_prices set active=true,updated_by=a where variant_id=p_id and not active returning *) select coalesce(jsonb_agg(to_jsonb(u)),'[]') into pa from u;perform public.catalogue_audit(a,'CATALOGUE_VARIANT_UPDATED','PRODUCT_VARIANT',r.id,jsonb_build_object('variant',to_jsonb(b),'prices',pb),jsonb_build_object('variant',to_jsonb(r),'activated_prices',pa));return r;end $$;
create or replace function public.catalogue_archive_variant(p_id uuid) returns public.product_variants language plpgsql security definer set search_path=public as $$ declare a uuid:=public.require_catalogue_manager();b public.product_variants;r public.product_variants;pb jsonb;pa jsonb;begin select v.* into b from public.product_variants v join public.products p on p.id=v.product_id where v.id=p_id for update of p,v;if not found then raise exception 'Product variant not found';end if;perform 1 from public.stock_buckets where product_id=b.product_id and variant_id=p_id and quantity>0 for key share;if found then raise exception 'A variant with current non-serialized inventory cannot be archived';end if;perform 1 from public.serialized_units where product_id=b.product_id and variant_id=p_id and status='AVAILABLE' for key share;if found then raise exception 'A variant with current available serialized inventory cannot be archived';end if;select coalesce(jsonb_agg(to_jsonb(x)),'[]') into pb from (select * from public.catalogue_prices where variant_id=p_id and active for update) x;with u as (update public.catalogue_prices set active=false,updated_by=a where variant_id=p_id and active returning *) select coalesce(jsonb_agg(to_jsonb(u)),'[]') into pa from u;update public.product_variants set active=false where id=p_id returning * into r;perform public.catalogue_audit(a,'CATALOGUE_VARIANT_ARCHIVED','PRODUCT_VARIANT',r.id,jsonb_build_object('variant',to_jsonb(b),'prices',pb),jsonb_build_object('variant',to_jsonb(r),'prices',pa));return r;end $$;

create or replace function public.catalogue_set_price(p_product uuid,p_variant uuid,p_condition public.product_condition,p_price numeric,p_active boolean default true) returns public.catalogue_prices language plpgsql security definer set search_path=public as $$ declare a uuid:=public.require_catalogue_manager();b public.catalogue_prices;r public.catalogue_prices;v public.product_variants;active_count integer;begin perform 1 from public.products where id=p_product for update;if not found then raise exception 'Product not found';end if;if p_variant is not null then select * into v from public.product_variants where id=p_variant and product_id=p_product for update;if not found then raise exception 'Variant does not belong to product';end if;perform 1 from public.catalogue_prices where variant_id=p_variant for update;else perform 1 from public.product_variants where product_id=p_product and active for update;if p_active and found then raise exception 'Product-level prices are not permitted while active variants exist';end if;end if;select * into b from public.catalogue_prices where product_id=p_product and variant_id is not distinct from p_variant and condition=p_condition for update;if p_active then if not exists(select 1 from public.products where id=p_product and active) then raise exception 'An active catalogue price requires an active product';end if;if p_variant is not null and not v.active then raise exception 'An active variant price requires an active matching variant';end if;end if;if found and not p_active and b.active and p_variant is not null and v.active then select count(*) into active_count from public.catalogue_prices where variant_id=p_variant and active and id<>b.id;if active_count=0 then raise exception 'Archive the variant to remove its final active price';end if;end if;if found then update public.catalogue_prices set selling_price=p_price,active=p_active,updated_by=a where id=b.id returning * into r;perform public.catalogue_audit(a,'CATALOGUE_PRICE_UPDATED','CATALOGUE_PRICE',r.id,to_jsonb(b),to_jsonb(r));else insert into public.catalogue_prices(product_id,variant_id,condition,selling_price,active,created_by,updated_by) values(p_product,p_variant,p_condition,p_price,p_active,a,a) returning * into r;perform public.catalogue_audit(a,'CATALOGUE_PRICE_CREATED','CATALOGUE_PRICE',r.id,null,to_jsonb(r));end if;return r;end $$;

drop function public.staff_catalog_lookup();
create function public.staff_catalog_lookup(p_search text default null) returns table(product_id uuid,product_name text,product_sku text,product_barcode text,brand_name text,category_name text,serialized boolean,variant_id uuid,variant_label text,variant_sku text,variant_barcode text,condition public.product_condition,quantity integer,selling_price numeric) language plpgsql security definer set search_path=public as $$ begin perform public.require_active_profile();return query select p.id,p.name,p.sku,p.barcode,b.name,c.name,p.serialized,v.id,v.label,v.sku,v.barcode,cp.condition,coalesce(sb.quantity,0),cp.selling_price from public.products p left join public.brands b on b.id=p.brand_id and b.active left join public.categories c on c.id=p.category_id and c.active left join public.product_variants v on v.product_id=p.id and v.active join public.catalogue_prices cp on cp.product_id=p.id and cp.variant_id is not distinct from v.id and cp.active left join public.stock_buckets sb on sb.product_id=p.id and sb.variant_id is not distinct from v.id and sb.condition=cp.condition where p.active and not p.serialized and (p_search is null or p.name ilike '%'||btrim(p_search)||'%' or p.sku=upper(btrim(p_search)) or p.barcode=upper(btrim(p_search)) or v.sku=upper(btrim(p_search)) or v.barcode=upper(btrim(p_search))) order by p.name,v.label nulls first,cp.condition;end $$;

revoke all on function public.require_catalogue_manager(),public.lock_active_parents(uuid,uuid),public.catalogue_audit(uuid,text,text,uuid,jsonb,jsonb),public.forbid_catalogue_delete() from public,anon,authenticated;
revoke all on function public.catalogue_create_category(text),public.catalogue_update_category(uuid,text,boolean),public.catalogue_create_brand(text),public.catalogue_update_brand(uuid,text,boolean),public.catalogue_create_product(text,text,text,text,text,uuid,uuid,boolean,integer,integer),public.catalogue_update_product(uuid,text,text,text,text,text,uuid,uuid,boolean,integer,integer,boolean),public.catalogue_archive_product(uuid),public.catalogue_create_variant(uuid,text,text,text,jsonb),public.catalogue_update_variant(uuid,text,text,text,jsonb,boolean),public.catalogue_archive_variant(uuid),public.catalogue_set_price(uuid,uuid,public.product_condition,numeric,boolean),public.staff_catalog_lookup(text) from public,anon,authenticated;
grant execute on function public.catalogue_create_category(text),public.catalogue_update_category(uuid,text,boolean),public.catalogue_create_brand(text),public.catalogue_update_brand(uuid,text,boolean),public.catalogue_create_product(text,text,text,text,text,uuid,uuid,boolean,integer,integer),public.catalogue_update_product(uuid,text,text,text,text,text,uuid,uuid,boolean,integer,integer,boolean),public.catalogue_archive_product(uuid),public.catalogue_create_variant(uuid,text,text,text,jsonb),public.catalogue_update_variant(uuid,text,text,text,jsonb,boolean),public.catalogue_archive_variant(uuid),public.catalogue_set_price(uuid,uuid,public.product_condition,numeric,boolean),public.staff_catalog_lookup(text) to authenticated;
